const imagespart6=[
    {id:1, url:require("./assets/images-page-5/page5 row1-1.jpg")},
    {id:2, url:require("./assets/images-page-5/page5 row1-2.jpg")},
    {id:3, url:require("./assets/images-page-5/page5 row1-3.jpg")},
    {id:4, url:require("./assets/images-page-5/page5 row1-4.jpg")},
    {id:5, url:require("./assets/images-page-5/page5 row1-5.jpg")},
    {id:6, url:require("./assets/images-page-5/page5 row1-6.jpg")},
    {id:7, url:require("./assets/images-page-5/page5 row2-1.jpg")},
    {id:8, url:require("./assets/images-page-5/page5 row2-2.jpg")},
    {id:9, url:require("./assets/images-page-5/page5 row2-3.jpg")},
    {id:10, url:require("./assets/images-page-5/page5 row2-4.jpg")},
    {id:11, url:require("./assets/images-page-5/page5 row3-1.jpg")},
    {id:12, url:require("./assets/images-page-5/page5 row3-2.jpg")},
    {id:13, url:require("./assets/images-page-5/page5 row3-3.jpg")},
    {id:14, url:require("./assets/images-page-5/page5 row3-4.jpg")},
    {id:15, url:require("./assets/images-page-5/page5 row4-1.jpg")},
    {id:16, url:require("./assets/images-page-5/page5 row4-2.jpg")},
    {id:17, url:require("./assets/images-page-5/page5 row4-3.jpg")},
    {id:18, url:require("./assets/images-page-5/page5 row4-4.jpg")},
    {id:19, url:require("./assets/images-page-5/page5 row5-1.jpg")},
    {id:20, url:require("./assets/images-page-5/page5 row5-2.jpg"),},
    {id:21, url:require("./assets/images-page-5/page5 row5-3.jpg"),},
    {id:22, url:require("./assets/images-page-5/page5 row6-1.jpg"),},
    {id:23, url:require("./assets/images-page-5/page5 row6-2.jpg"),},
    {id:24, url:require("./assets/images-page-5/page5 row6-3.jpg"),},
    {id:25, url:require("./assets/images-page-5/page5 row6-4.jpg"),},
    {id:26, url:require("./assets/images-page-5/page5 row7-1.jpg"),},
    {id:27, url:require("./assets/images-page-5/page5 row7-2.jpg"),},
    {id:28, url:require("./assets/images-page-5/page5 row7-3.jpg"),},
    {id:29, url:require("./assets/images-page-5/page5 row7-4.jpg"),},
    {id:30, url:require("./assets/images-page-5/page5 row8-1.jpg"),price:"₹280",name:"Feston Nature set of 5"},
    {id:31, url:require("./assets/images-page-5/page5 row8-2.jpg"),price:"₹99",name:"Feston Nature set of 5"},
    {id:32, url:require("./assets/images-page-5/page5 row8-3.jpg"),price:"₹280",name:"Feston Nature set of 5"},
    {id:33, url:require("./assets/images-page-5/page5 row8-4.jpg"),price:"₹1,799",name:"Feston Nature set of 5"},
    {id:34, url:require("./assets/images-page-5/page5 row8-5.jpg"),price:"₹280",name:"Feston Nature set of 5"},
]
export default imagespart6;